### ISSUE TITLE
JLink Windows device detection no longer works properly

### ISSUE THREAD

**Issue by cmonr** [ARMmbed/mbed-ls#385]
Since https://github.com/ARMmbed/mbed-ls/commit/758394e915c3d6bf7e116e57385987468295cf81, running `mbedls` in a Windows env does not detect JLink targets properly.

Before the commit:
```
C:\Users\redacted\tmp\mbed-ls>mbedls
+-----------------+----------------------+-------------+-------------+--------------------------+-----------------+
| platform_name   | platform_name_unique | mount_point | serial_port | target_id                | daplink_version |
+-----------------+----------------------+-------------+-------------+--------------------------+-----------------+
| EFM32GG_STK3700 | EFM32GG_STK3700[0]   | E:          | COM3        | 2015009F00004A2AD6C679E5 | 0.14.3          |
+-----------------+----------------------+-------------+-------------+--------------------------+-----------------+
```

After the commit:
```
C:\Users\redacted\tmp\mbed-ls>mbedls
WARNING:mbedls.lstools_base:No valid file found to update JLink device details
+---------------+----------------------+-------------+-------------+--------------+-----------------+
| platform_name | platform_name_unique | mount_point | serial_port | target_id    | daplink_version |
+---------------+----------------------+-------------+-------------+--------------+-----------------+
| LPC2368       | LPC2368[0]           | E:          | COM3        | 000440018986 | unknown         |
+---------------+----------------------+-------------+-------------+--------------+-----------------+
```

The above output is the same for `release-version-1.5.0`.

However, the output does change when using `release-version-1.5.1`:
```
C:\Users\redacted\tmp\mbed-ls>mbedls
WARNING:mbedls.lstools_base:No valid file found to update JLink device details
+---------------+----------------------+-------------+-------------+--------------+-----------------+
| platform_name | platform_name_unique | mount_point | serial_port | target_id    | daplink_version |
+---------------+----------------------+-------------+-------------+--------------+-----------------+
| unknown       | None[0]              | E:          | COM3        | 000440018986 | unknown         |
+---------------+----------------------+-------------+-------------+--------------+-----------------+
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1509

**Comment by bridadan** [comment]
Pretty sure this should be fixed? @cmonr can you check?

**Comment by cmonr** [comment]
Works with 1.6.0!

**Comment by bridadan** [comment]
Thanks for checking!

**Comment by srikav** [comment]
**from what i am seeing the problem still exists**

Command-line code management tool for ARM mbed OS - http://www.mbed.com
version 1.8.3

WARNING:mbedls.lstools_base:No valid file found to update JLink device details
| platform_name | platform_name_unique | mount_point | serial_port | target_id                | daplink_version |
|---------------|----------------------|-------------|-------------|--------------------------|-----------------|
| TB_SENSE_12   | TB_SENSE_12[0]       | E:          | COM5        | 2041010A0001EC21D752DFBA | 1.3.0           |

can you please point me in the right direction to fix the issue.

**Comment by charlottewai** [comment]
Hi, any update on this? I am seeing this on version 1.10.2 as well.

**Comment by isdsi** [comment]
Has this solved the problem? I tried it on pyocd 0.28.3. But It doesn't work.
